### ISSUE TITLE
Per Fedora 29 Repo??

### ISSUE THREAD

**Issue by IvanDeFelice76** [rpmsphere/rpmsphere.github.io#1]
I wanted to know how to insert the most correct version of Fedora 29 Repositories to avoid any problems

**Comment by bluebat** [comment]
rpm -Uvh https://github.com/rpmsphere/noarch/raw/master/r/rpmsphere-release-29-2.noarch.rpm

**Comment by IvanDeFelice76** [comment]
> rpm -Uvh https://github.com/rpmsphere/noarch/raw/master/r/rpmsphere-release-29-2.noarch.rpm

Tenks
