### ISSUE TITLE
License of the repo

### ISSUE THREAD

**Issue by telometto** [rpmsphere/rpmsphere.github.io#2]
Hi.

I was just wondering about the licensing of the repository. I opened the `rpm` and noticed in the Software Center that it says 'Proprietary' - is this correct?

**Comment by bluebat** [comment]
Which package or file?

**Comment by telometto** [comment]
https://github.com/rpmsphere/noarch/raw/master/r/rpmsphere-release-34-1.noarch.rpm

**Comment by bluebat** [comment]
user> rpm -qpi https://github.com/rpmsphere/noarch/raw/master/r/rpmsphere-release-34-1.noarch.rpm
Name        : rpmsphere-release
Version     : 34
Release     : 1
Architecture: noarch
Install Date: (not installed)
Group       : System Environment/Base
Size        : 724
License     : Public Domain
Signature   : (none)
Source RPM  : rpmsphere-release-34-1.src.rpm
Build Date  : Sat Apr 17 03:09:21 2021
Build Host  : localhost.localdomain
URL         : https://github.com/rpmsphere
Summary     : RPM Sphere release file
Description :
RPM Sphere release yum configs to define the repository.
Collection of extra packages for Fedora Linux.
Feel free to promote them in any form.

**Comment by telometto** [comment]
I was just wondering because, as you can see from the screenshot, it says 'Proprietary' in the SC.

![Screenshot from 2021-09-09 08-56-45](https://user-images.githubusercontent.com/65364211/132637739-11cfe6b7-9a30-445d-b43a-930241f648d8.png)

**Comment by bluebat** [comment]
I have never used Software Center :). Maybe "Public Domain" is not a good license name.
What it says for package "fedora-release" or "rpmfusion-free-release" ?

**Comment by telometto** [comment]
I just had to ask to be sure that it wasn't proprietary ^_^

Anyway, under you can see what the RPM Fusion non-free repo says.

![Screenshot from 2021-09-09 09-15-57](https://user-images.githubusercontent.com/65364211/132640407-2c9fcb8c-7cb5-4f97-ae09-929dc2c7f896.png)

**Comment by bluebat** [comment]
Anyway, changed to BSD.
