### ISSUE TITLE
update/rebuild request: gnustep-gui

### ISSUE THREAD

**Issue by hairmare** [rpmsphere/rpmsphere.github.io#3]
I'm trying to compile PikoPixel on FC36 with the least possible amount of local build-chain.

What would i need to patch to get an updated `gnustep-gui` package that doesn't `Problem: conflicting requests` with `gnustep-base` from `fedora`? 

It looks like `fedora` is ahead of `rpmsphere-fc36` wrt the gnustep version/build. maybe a rebuild is enough or the -gui package needs bumping as well. Is this even the right place for this issue?

**Comment by bluebat** [comment]
I can't rebuild gnustep-gui on F36. It seems to be a bug in gnustep-make. I have submitted a report at https://bugzilla.redhat.com/show_bug.cgi?id=2124395

**Comment by bluebat** [comment]
Fixed. Please update.
